[
    {
        "content": "<p>Did I miss something in my email (quite possible) or is the JupyterHub unexpectedly down?  I'm seeing Spawner timeouts:</p>\n<p><a href=\"/user_uploads/2/32/dfuLGOsOblLfNPUEfJBNTPak/Screen-Shot-2021-01-26-at-12.29.43-PM.png\" target=\"_blank\" title=\"Screen-Shot-2021-01-26-at-12.29.43-PM.png\">Screen-Shot-2021-01-26-at-12.29.43-PM.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/32/dfuLGOsOblLfNPUEfJBNTPak/Screen-Shot-2021-01-26-at-12.29.43-PM.png\" target=\"_blank\" title=\"Screen-Shot-2021-01-26-at-12.29.43-PM.png\"><img src=\"/user_uploads/2/32/dfuLGOsOblLfNPUEfJBNTPak/Screen-Shot-2021-01-26-at-12.29.43-PM.png\"></a></div>",
        "id": 24214,
        "sender_full_name": "Kevin Paul",
        "timestamp": 1611691562
    },
    {
        "content": "<p>DAV is definitely up</p>",
        "id": 24218,
        "sender_full_name": "Matt Long",
        "timestamp": 1611695779
    },
    {
        "content": "<p>Cheyenne?</p>",
        "id": 24219,
        "sender_full_name": "Kevin Paul",
        "timestamp": 1611696481
    },
    {
        "content": "<p>I can also get a session on Cheyenne</p>",
        "id": 24220,
        "sender_full_name": "Matt Long",
        "timestamp": 1611698366
    },
    {
        "content": "<p>I'll try it again.</p>",
        "id": 24222,
        "sender_full_name": "Kevin Paul",
        "timestamp": 1611698458
    },
    {
        "content": "<p>Yep.  It works for me, now, too.  Thanks!</p>",
        "id": 24223,
        "sender_full_name": "Kevin Paul",
        "timestamp": 1611698527
    },
    {
        "content": "<p>I am unable to access <a href=\"http://jupyterhub.ucar.edu\">jupyterhub.ucar.edu</a>. Just filed a CISLHelp ticket. <span class=\"user-group-mention\" data-user-group-id=\"6\">@hpcd</span></p>",
        "id": 46813,
        "sender_full_name": "Matt Long",
        "timestamp": 1636640129
    },
    {
        "content": "<p><a href=\"http://jupyterhub.hpc.ucar.edu\">jupyterhub.hpc.ucar.edu</a>?</p>",
        "id": 46814,
        "sender_full_name": "Jared Baker",
        "timestamp": 1636642545
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"14\">@Matt Long</span></p>",
        "id": 46815,
        "sender_full_name": "Jared Baker",
        "timestamp": 1636642980
    },
    {
        "content": "<p>yes, sorry: <a href=\"http://jupyterhub.hpc.ucar.edu\">jupyterhub.hpc.ucar.edu</a>.</p>\n<p>It's back now. There was a notifier from Peter Buss reporting some network work right around the same time.</p>",
        "id": 46816,
        "sender_full_name": "Matt Long",
        "timestamp": 1636643117
    },
    {
        "content": "<p>Do you have a help-desk ticket number?</p>",
        "id": 46817,
        "sender_full_name": "Jared Baker",
        "timestamp": 1636643392
    },
    {
        "content": "<p>RC-11190</p>",
        "id": 46818,
        "sender_full_name": "Matt Long",
        "timestamp": 1636643716
    },
    {
        "content": "<p>Okay, were you trying to authenticate during this time?</p>",
        "id": 46819,
        "sender_full_name": "Jared Baker",
        "timestamp": 1636644326
    },
    {
        "content": "<p>No, I don't think so. I was already behind the auth layer.</p>",
        "id": 46824,
        "sender_full_name": "Matt Long",
        "timestamp": 1636647016
    },
    {
        "content": "<p>I cannot log in to <a href=\"http://jupyterhub.hpc.ucar.edu\">jupyterhub.hpc.ucar.edu</a> this morning. Keep getting a timeout error at authentication (RC-11220).</p>",
        "id": 46898,
        "sender_full_name": "Stephen Yeager",
        "timestamp": 1636736189
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"34\">Stephen Yeager</span> <a href=\"#narrow/stream/16-jupyter/topic/Hub.20down.3F/near/46898\">said</a>:</p>\n<blockquote>\n<p>I cannot log in to <a href=\"http://jupyterhub.hpc.ucar.edu\">jupyterhub.hpc.ucar.edu</a> this morning. Keep getting a timeout error at authentication (RC-11220).</p>\n</blockquote>\n<p>I've been having a hard time accessing the hub as well but Chrome has been giving me a message of \"Your connection is not private\" instead (with or without a vpn connection)</p>",
        "id": 46916,
        "sender_full_name": "Zephyr Sylvester",
        "timestamp": 1636739998
    },
    {
        "content": "<p>I've got a CISL ticket in regarding authentication timeouts. That's unfortunately outside the scope of HPCD.</p>",
        "id": 46922,
        "sender_full_name": "Jared Baker",
        "timestamp": 1636740198
    },
    {
        "content": "<p>I think you should be able to authenticate now.</p>",
        "id": 46927,
        "sender_full_name": "Jared Baker",
        "timestamp": 1636740632
    },
    {
        "content": "<p>I have also been having issues accessing the hub on chrome with the issue of the connection not being private. It works fine on firefox, but I prefer to use chrome.  I think my chrome is up-to-date.  Has anyone found a solution?</p>",
        "id": 46998,
        "sender_full_name": "Isla Simpson",
        "timestamp": 1636833227
    },
    {
        "content": "<p>I am also still getting this message on Chrome. Any way to resolve this would be greatly appreciated!</p>",
        "id": 47032,
        "sender_full_name": "Maria Molina",
        "timestamp": 1637005703
    },
    {
        "content": "<p>If you are on chrome, you should be able to use the <a href=\"http://jupyterhub.hpc.ucar.edu\">jupyterhub.hpc.ucar.edu</a> link - I have been using that.</p>",
        "id": 47052,
        "sender_full_name": "Max Grover",
        "timestamp": 1637015851
    },
    {
        "content": "<p>thanks, <span class=\"user-mention\" data-user-id=\"134\">@Max Grover</span> ! seems to be working for me now too! maybe I used the wrong link</p>",
        "id": 47069,
        "sender_full_name": "Maria Molina",
        "timestamp": 1637019363
    },
    {
        "content": "<p>Is the hub down for other folks? I keep getting a 504 Gateway Timeout</p>",
        "id": 49410,
        "sender_full_name": "Adrianna Foster",
        "timestamp": 1642546886
    },
    {
        "content": "<p>me too for about the last hour; I submitted a cisl help ticket.</p>",
        "id": 49411,
        "sender_full_name": "Brian Bonnlander",
        "timestamp": 1642546921
    },
    {
        "content": "<p>It looks like Casper is down</p>",
        "id": 49413,
        "sender_full_name": "Max Grover",
        "timestamp": 1642547418
    },
    {
        "content": "<p>PBS is having issues checking out licenses, so JupyterHub jobs will fail after a 10-minute timeout for server to start.</p>",
        "id": 49414,
        "sender_full_name": "Jared Baker",
        "timestamp": 1642547864
    },
    {
        "content": "<p>Anyone else seeing Gateway Timeout 504 on jupyterhub?</p>",
        "id": 49421,
        "sender_full_name": "Brian Bonnlander",
        "timestamp": 1642623699
    },
    {
        "content": "<p>OK, I can login to jupyterhub now, never mind...</p>",
        "id": 49422,
        "sender_full_name": "Brian Bonnlander",
        "timestamp": 1642624545
    }
]