[
    {
        "content": "<p>Hello, I was using jupyterhub on casper today and I got kicked off and now it won't let me start a new session. It's stuck on the \"Your server is starting up\" page, which eventually times out. I've got a new jupyterhub session going on Cheyenne, but I will need to be back on casper to access certain files. <span class=\"user-mention\" data-user-id=\"154\">@Jared Baker</span> , would you be able to help me sort this out?</p>",
        "id": 32879,
        "sender_full_name": "Kristen Krumhardt",
        "timestamp": 1622141658
    },
    {
        "content": "<p>I'm also having issues getting onto casper with jupyterhub.  Stuck on \"Your server is starting up\" with a red bar.</p>",
        "id": 32880,
        "sender_full_name": "Isla Simpson",
        "timestamp": 1622141869
    },
    {
        "content": "<p>Others say their jobs that were running crashed</p>",
        "id": 32881,
        "sender_full_name": "Maria Molina",
        "timestamp": 1622142104
    },
    {
        "content": "<p>Might not be jupyter specific, but PBS on casper because no jobs show up for me with qstat @casper</p>",
        "id": 32882,
        "sender_full_name": "Maria Molina",
        "timestamp": 1622142278
    },
    {
        "content": "<p>CISL resource status page (<a href=\"https://www2.cisl.ucar.edu/user-support/cisl-resource-status\" target=\"_blank\" title=\"https://www2.cisl.ucar.edu/user-support/cisl-resource-status\">https://www2.cisl.ucar.edu/user-support/cisl-resource-status</a>) shows Casper job scheduling system is down.</p>",
        "id": 32883,
        "sender_full_name": "Stephen Yeager",
        "timestamp": 1622142804
    },
    {
        "content": "<p>Thanks <span class=\"user-mention\" data-user-id=\"34\">@Stephen Yeager</span> !</p>",
        "id": 32884,
        "sender_full_name": "Maria Molina",
        "timestamp": 1622142886
    },
    {
        "content": "<p>Yes, something more related to PBS as noted. We're working the issue.</p>",
        "id": 32885,
        "sender_full_name": "Jared Baker",
        "timestamp": 1622145309
    },
    {
        "content": "<p>I've had multiple occurrences of \"Server unavailable or unreachable\" errors this morning with jupyterhub on casper batch nodes.<br>\nAre others experiencing this as well?</p>\n<p>An aspect of these errors that is confusing to me is that the underlying casper batch job is still running.</p>",
        "id": 33303,
        "sender_full_name": "Keith Lindsay",
        "timestamp": 1622740664
    },
    {
        "content": "<p>Me too. I've gotten kicked off 3 times now...  yep, like <span class=\"user-mention\" data-user-id=\"31\">@Keith Lindsay</span> ,  I just looked and my jobs are still running on casper too.</p>",
        "id": 33304,
        "sender_full_name": "Kristen Krumhardt",
        "timestamp": 1622740842
    },
    {
        "content": "<p>me three</p>",
        "id": 33305,
        "sender_full_name": "Isla Simpson",
        "timestamp": 1622741063
    },
    {
        "content": "<p>When attempting to restart, I sometimes get a popup with the following message</p>\n<div class=\"codehilite\"><pre><span></span>Spawn failed: The Jupyter batch job has disappeared while pending in the queue or died immediately after starting.\n</pre></div>",
        "id": 33306,
        "sender_full_name": "Keith Lindsay",
        "timestamp": 1622741328
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"154\">@Jared Baker</span> any idea of what is going on there?</p>",
        "id": 33307,
        "sender_full_name": "Max Grover",
        "timestamp": 1622741354
    },
    {
        "content": "<p>Same here, started on and off yesterday pm for me....</p>",
        "id": 33308,
        "sender_full_name": "Yassir Eddebbar",
        "timestamp": 1622741400
    },
    {
        "content": "<p>Do you have approximate times for these this morning?</p>",
        "id": 33309,
        "sender_full_name": "Jared Baker",
        "timestamp": 1622741477
    },
    {
        "content": "<p>Maybe around 11:30?</p>",
        "id": 33310,
        "sender_full_name": "Jared Baker",
        "timestamp": 1622741540
    },
    {
        "content": "<p>There were some PBS woes earlier this morning, but I can go digging more.</p>",
        "id": 33311,
        "sender_full_name": "Jared Baker",
        "timestamp": 1622741566
    },
    {
        "content": "<p>Mine have all happened between 9 and 11am</p>",
        "id": 33312,
        "sender_full_name": "Kristen Krumhardt",
        "timestamp": 1622741780
    },
    {
        "content": "<p>Around 11:20 for me.</p>",
        "id": 33313,
        "sender_full_name": "Isla Simpson",
        "timestamp": 1622742160
    },
    {
        "content": "<p>It was working well till ~10:30am-present</p>",
        "id": 33314,
        "sender_full_name": "Yassir Eddebbar",
        "timestamp": 1622742168
    },
    {
        "content": "<p>One of the occurrences for me was right before I posted, so about 11:15.<br>\nI'm not sure about the times before that.</p>",
        "id": 33316,
        "sender_full_name": "Keith Lindsay",
        "timestamp": 1622743380
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"154\">@Jared Baker</span> it is working for me now</p>",
        "id": 33322,
        "sender_full_name": "Max Grover",
        "timestamp": 1622745957
    },
    {
        "content": "<p>Okay, I'm still skeptical on a number of things right now. But I'll post more once I feel a bit more confident.</p>",
        "id": 33323,
        "sender_full_name": "Jared Baker",
        "timestamp": 1622746012
    },
    {
        "content": "<p>I filed a CISL ticket yesterday at ~4pm reporting Jupyterhub instability on casper batch nodes. This seems to be a very recurring issue.</p>",
        "id": 33391,
        "sender_full_name": "Stephen Yeager",
        "timestamp": 1622746435
    },
    {
        "content": "<p>Okay, I think I've got things back to a reasonable state over the course of the afternoon and tried to address some issues when the PBS server fails to communicate back to the JupyterHub server. Hopefully this helps with stability.</p>",
        "id": 33418,
        "sender_full_name": "Jared Baker",
        "timestamp": 1622763186
    },
    {
        "content": "<p>Thanks <span class=\"user-mention\" data-user-id=\"154\">@Jared Baker</span>  Quite stable this pm on my end!</p>",
        "id": 33419,
        "sender_full_name": "Yassir Eddebbar",
        "timestamp": 1622763703
    },
    {
        "content": "<p>I'm having the same error message as <span class=\"user-mention\" data-user-id=\"31\">@Keith Lindsay</span> reported above this morning... :/</p>",
        "id": 35348,
        "sender_full_name": "Rosie Fisher",
        "timestamp": 1624439512
    }
]