[
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"154\">@Jared Baker</span>, I am having an issue on JHub: notebooks seem to open in $HOME—not the directory where they actually reside on disk.</p>",
        "id": 54843,
        "sender_full_name": "Matt Long",
        "timestamp": 1652394081
    },
    {
        "content": "<p>I also noticed this issue this morning</p>",
        "id": 54846,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1652394301
    },
    {
        "content": "<p>Hmm. Okay. I noticed a ticket on it. I'm preoccupied right now, but can have a closer look later.</p>",
        "id": 54848,
        "sender_full_name": "Jared Baker",
        "timestamp": 1652394606
    },
    {
        "content": "<p>I just submitted a ticket that could be a related issue having to do with the default project account used for jhublogin sessions. For some reason, for me it is no longer using the project code set under <code>DAV_PROJECT</code> to start a server on a casper login node.</p>",
        "id": 54853,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1652395328
    },
    {
        "content": "<p><span class=\"user-group-mention\" data-user-group-id=\"6\">@hpcd</span>, any updates on when you might expect this issue to be fixed?</p>",
        "id": 54956,
        "sender_full_name": "Matt Long",
        "timestamp": 1652721092
    },
    {
        "content": "<p>Trying to understand if it's a bug in JupyterHub configuration or Jupyter Lab itself.</p>",
        "id": 54957,
        "sender_full_name": "Jared Baker",
        "timestamp": 1652721138
    },
    {
        "content": "<p>@all, Jared tells me that this issue has been resolved!</p>",
        "id": 54982,
        "sender_full_name": "Matt Long",
        "timestamp": 1652731555
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"14\">@Matt Long</span> Did this get resolved? I don't seem to be able to access data relative to my working directory - all paths start from home.</p>",
        "id": 55864,
        "sender_full_name": "Daniel Marsh",
        "timestamp": 1654117402
    },
    {
        "content": "<p>Well, not sure what changed but even though I started a new server this afternoon, it took restarting the kernel to return to the original behaviour of referencing files relative to the current working directory.  So I guess it's been resolved!</p>",
        "id": 55868,
        "sender_full_name": "Daniel Marsh",
        "timestamp": 1654120232
    },
    {
        "content": "<p>I experienced the issue again, but can't say for sure whether it was attributable to lack of restarting my server. Restarting the server seems to reliably eliminate the problem—but we should note if it continues to occur.</p>",
        "id": 55870,
        "sender_full_name": "Matt Long",
        "timestamp": 1654127221
    }
]