[
    {
        "content": "<p>Hi,</p>\n<p>I'm trying to save a dataArray to a zarr file, and have been able to do this in the past with similar code.  However, lately I've run into this issue which I cannot seem to resolve.</p>\n<p>Say my DataArray looks like this: </p>\n<p>aw_oceanT_global<br>\nxarray.DataArraytime: 3600 z_t:  60<br>\n                     Array  Chunk<br>\nBytes   1.65 MiB    480 B<br>\nShape   (3600, 60)  (1, 60)<br>\nCount   154875 Tasks    3600 Chunks<br>\nType    float64 numpy.ndarray   </p>\n<p>I do :</p>\n<p>aw_oceanT_global.unify_chunks()<br>\naw_oceanT_global.to_dataset(name='TEMP').chunk({'z_t':-1}).to_zarr('/glade/scratch/mberdahl/127kaH11/TEMP/aw_oceanT_global_timeseries_H11.zarr', mode='w')</p>\n<p>But receive the following error (just the top bit of it):<br>\ndistributed.utils - ERROR - 'str' object has no attribute 'text'<br>\nTraceback (most recent call last):<br>\n  File \"/glade/work/mberdahl/miniconda/envs/pangeo/lib/python3.9/site-packages/distributed/utils.py\", line 681, in log_errors<br>\n    yield<br>\n  File \"/glade/work/mberdahl/miniconda/envs/pangeo/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py\", line 346, in update<br>\n    self.root.title.text = title<br>\nAttributeError: 'str' object has no attribute 'text'<br>\ndistributed.utils - ERROR - 'str' object has no attribute 'text'<br>\nTraceback (most recent call last):<br>\n  File \"/glade/work/mberdahl/miniconda/envs/pangeo/lib/python3.9/site-packages/distributed/utils.py\", line 681, in log_errors<br>\n    yield<br>\n  File \"/glade/work/mberdahl/miniconda/envs/pangeo/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py\", line 3417, in status_doc<br>\n    cluster_memory.update()</p>\n<p>Looks like I'm running into memory issues maybe?bBut this DataArray isn't any bigger than other arrays I've had success with with the same methods.  Any thoughts appreciated!</p>",
        "id": 49738,
        "sender_full_name": "Mira Berdahl",
        "timestamp": 1643241178
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"259\">@Mira Berdahl</span>, I don't know why this is failing by looking at the traceback. Can you provide a reproducible test case or a pointer to the notebook you're using?</p>",
        "id": 49741,
        "sender_full_name": "Anderson Banihirwe",
        "timestamp": 1643243100
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"13\">@Anderson Banihirwe</span> , the path to the notebook is:<br>\n/glade/u/home/mberdahl/FirstLook_LIGruns/DASK_scripts/TryAreaWeightingAvg.ipynb<br>\nThanks for taking a look!</p>",
        "id": 49743,
        "sender_full_name": "Mira Berdahl",
        "timestamp": 1643251897
    }
]