<html>
<head><meta charset="utf-8"><title>history saving thread error · jupyterlab-hub · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://127.0.0.1:4000/html/stream/16-jupyterlab-hub/index.html">jupyterlab-hub</a></h2>
<h3>Topic: <a href="http://127.0.0.1:4000/html/stream/16-jupyterlab-hub/topic/history.20saving.20thread.20error.html">history saving thread error</a></h3>

<hr>

<base href="https://zulip2.cloud.ucar.edu">

<head><link href="http://127.0.0.1:4000/style.css" rel="stylesheet"></head>

<a name="20998"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/16-jupyterlab-hub/topic/history%20saving%20thread%20error/near/20998" class="zl"><img src="http://127.0.0.1:4000/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Daniel Kennedy <a href="http://127.0.0.1:4000/html/stream/16-jupyterlab-hub/topic/history.20saving.20thread.20error.html#20998">(Nov 05 2020 at 18:11)</a>:</h4>
<p>In case this trips anyone else up: I ran into "The history saving thread hit an unexpected error (OperationalError('disk I/O error')).History will not be written to the database.", which was the result of reaching my storage quota on /glade. Can use gladequota on cheyenne to check your quotas</p>



<hr><p>Last updated: Jan 27 2025 at 22:16 UTC</p>
</html>