<html>
<head><meta charset="utf-8"><title>intake-esm stalls on to_dataset_dict · python-questions · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://127.0.0.1:4000/html/stream/10-python-questions/index.html">python-questions</a></h2>
<h3>Topic: <a href="http://127.0.0.1:4000/html/stream/10-python-questions/topic/intake-esm.20stalls.20on.20to_dataset_dict.html">intake-esm stalls on to_dataset_dict</a></h3>

<hr>


<head><link href="http://127.0.0.1:4000/style.css" rel="stylesheet"></head>

<a name="73529"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20stalls%20on%20to_dataset_dict/near/73529" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Stephen Yeager <a href="http://127.0.0.1:4000/html/stream/10-python-questions/topic/intake-esm.20stalls.20on.20to_dataset_dict.html#73529">(Feb 03 2023 at 15:49)</a>:</h4>
<p>Notebooks that used to work to ingest CESM2-LE data using intake-esm are now failing after updating my environment. The <code>to_dataset_dict()</code> method stalls at 0% progress. The new environment uses intake-esm v2022.9.18, dask v2022.11.0, xarray v2023.1.0 and is here:  <br>
/glade/work/yeager/conda-envs/mypythonenv</p>
<p>A minimal notebook that demonstrates the problem is here: /glade/u/home/yeager/analysis/python/toshare/intake_freeze.ipynb</p>
<p>I don't know if the problem is related to an earlier (2020) reported <a href="https://github.com/intake/intake-esm/issues/219">issue</a> with intake-esm.</p>



<hr><p>Last updated: May 16 2025 at 17:14 UTC</p>
</html>