[
    {
        "content": "<p>I have an interesting case with WRF model files, and using the xWRF Python package (<a href=\"https://xwrf.readthedocs.io/en/latest/\">https://xwrf.readthedocs.io/en/latest/</a>). </p>\n<p>I'll use some toy code to demonstrate:</p>\n<div class=\"codehilite\"><pre><span></span><code>import xarray as xr\nds = xr.open_dataset(&#39;/glade/u/home/dadriaan/DOES_NOT_EXIST.nc&#39;)\n</code></pre></div>\n<p>The above code returns this:</p>\n<div class=\"codehilite\"><pre><span></span><code>FileNotFoundError: [Errno 2] No such file or directory: &#39;/glade/u/home/dadriaan/DOES_NOT_EXIST.nc&#39;\n</code></pre></div>\n<p>Now, another example (also for a file that DOES NOT EXIST):</p>\n<div class=\"codehilite\"><pre><span></span><code>import xarray as xr\nimport xwrf\nds = xr.open_dataset(&#39;/glade/u/home/wrfout_d01_2021-02-10_10:30:00&#39;).xwrf.postprocess()\n</code></pre></div>\n<p>The above code returns:</p>\n<div class=\"codehilite\"><pre><span></span><code>ValueError: did not find a match in any of xarray&#39;s currently installed IO backends [&#39;scipy&#39;]. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:\nhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html\nhttps://docs.xarray.dev/en/stable/user-guide/io.html\n</code></pre></div>\n<p>The tricky part here, is that the file I tried to read also DOES NOT EXIST, however the error returned to me is not helpful as a user and misleads me into thinking I have environment problems or engine issues, or something to that effect, rather than a file that's missing.</p>\n<p>I am wondering if it's worthwhile to make sure the <code>os.PathLike</code> object passed to <code>guess_engine</code> (<a href=\"https://github.com/pydata/xarray/blob/92c8b33eb464b09d6f8277265b16cae039ab57ee/xarray/backends/plugins.py#L147\">https://github.com/pydata/xarray/blob/92c8b33eb464b09d6f8277265b16cae039ab57ee/xarray/backends/plugins.py#L147</a>) exists before attempting the engine guess? If not, return the error similar to what's spit out from the <code>file_manager.py</code>?</p>\n<p>It might also make sense to move it up into <code>api.py</code> in <code>open_dataset</code>: <a href=\"https://github.com/pydata/xarray/blob/92c8b33eb464b09d6f8277265b16cae039ab57ee/xarray/backends/api.py#L550-L551\">https://github.com/pydata/xarray/blob/92c8b33eb464b09d6f8277265b16cae039ab57ee/xarray/backends/api.py#L550-L551</a></p>",
        "id": 86596,
        "sender_full_name": "Daniel Adriaansen",
        "timestamp": 1691009338
    }
]